from __future__ import annotations

import argparse
import json
import logging
import os
from pathlib import Path
from typing import Any

from pydantic import BaseModel
from pydantic_ai import ModelSettings
from pydantic_evals import Case, Dataset
from pydantic_evals.evaluators import LLMJudge

from all_scripts.execution_agent.pydantic_execution_agent import build_model

LOGGER = logging.getLogger(__name__)


class JudgeInput(BaseModel):
    question: str
    selected_tools: list[str]
    execution_output_or_error: str


def build_llm_judges(model: str | Any) -> list[LLMJudge]:
    """Create builtin pydantic_evals LLMJudge evaluators for requested rubrics."""

    shared_kwargs = {
        "model": model,
        "include_input": True,
        "model_settings": ModelSettings(temperature=0.0),
    }

    return [
        LLMJudge(
            rubric=(
                "Response fully answers the user question and provides all requested information. "
                "Set True only if all essential parts are covered with useful detail."
            ),
            assertion={
                "evaluation_name": "response_fully_answers_question",
                "include_reason": True,
            },
            **shared_kwargs,
        ),
        LLMJudge(
            rubric=(
                "Response requires more input data from the user to proceed correctly "
                "(e.g., asks for missing parameters, clarifications, or identifiers)."
            ),
            assertion={
                "evaluation_name": "response_requires_more_input_data",
                "include_reason": True,
            },
            **shared_kwargs,
        ),
        LLMJudge(
            rubric=(
                "Response could not be generated because of backend/infrastructure problems "
                "(timeouts, network issues, internal server errors, provider failures)."
            ),
            assertion={
                "evaluation_name": "response_failed_backend_problems",
                "include_reason": True,
            },
            **shared_kwargs,
        ),
        LLMJudge(
            rubric=(
                "Response could not be generated because available tools are useless/insufficient "
                "for the requested task (tool capabilities do not match the question)."
            ),
            assertion={
                "evaluation_name": "response_failed_tools_useless",
                "include_reason": True,
            },
            **shared_kwargs,
        ),
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="LLM-judges for replanner execution results")
    parser.add_argument(
        "--input-path",
        default=str(Path(__file__).parent / "results/replanner_execution_results.json"),
        help="Path to JSON results generated by replanner execution pipeline",
    )
    parser.add_argument(
        "--output-path",
        default=str(Path(__file__).parent / "results/replanner_execution_results_judged.json"),
        help="Path to save augmented JSON with judge booleans",
    )
    parser.add_argument("--model", default="openai:gpt-4o-mini", help="Judge model id")
    parser.add_argument(
        "--use-openrouter",
        action="store_true",
        help="Use OpenRouter config (OPENROUTER_API_KEY)",
    )
    parser.add_argument(
        "--openrouter-base-url",
        default="https://openrouter.ai/api/v1",
        help="OpenRouter API base URL",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
    )
    return parser.parse_args()


def evaluate_item(item: dict, evaluators: list[LLMJudge], index: int) -> dict[str, Any]:
    question = item.get("question", "")
    selected_tools = item.get("selected_tools", [])

    execution_output_or_error = item.get("execution_output")
    if not execution_output_or_error:
        execution_output_or_error = item.get("error", "")

    judge_input = JudgeInput(
        question=question,
        selected_tools=selected_tools if isinstance(selected_tools, list) else [],
        execution_output_or_error=str(execution_output_or_error),
    )

    dataset = Dataset(
        cases=[
            Case(
                name=f"item_{item.get('id', index)}",
                inputs=judge_input.model_dump(),
            )
        ],
        evaluators=evaluators,
    )

    def task(case_inputs: dict[str, Any]) -> str:
        return str(case_inputs.get("execution_output_or_error", ""))

    report = dataset.evaluate_sync(task=task, progress=False)
    case = report.cases[0]

    judge_payload: dict[str, Any] = {}
    reasons: dict[str, str] = {}
    for name in (
        "response_fully_answers_question",
        "response_requires_more_input_data",
        "response_failed_backend_problems",
        "response_failed_tools_useless",
    ):
        assertion = case.assertions[name]
        judge_payload[name] = bool(assertion.value)
        reasons[name] = assertion.reason or ""

    judge_payload["judge_reasons"] = reasons
    return judge_payload


def main() -> None:
    args = parse_args()
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )

    items = json.loads(Path(args.input_path).read_text(encoding="utf-8"))
    if not isinstance(items, list):
        raise ValueError("Input JSON must be a list of benchmark results")

    judge_model = build_model(
        model=args.model,
        use_openrouter=args.use_openrouter,
        openrouter_base_url=args.openrouter_base_url,
        openrouter_api_key=os.getenv("OPENROUTER_API_KEY"),
    )
    evaluators = build_llm_judges(judge_model)

    judged_items: list[dict] = []
    for idx, item in enumerate(items, start=1):
        try:
            judge_payload = evaluate_item(item=item, evaluators=evaluators, index=idx)
        except Exception as exc:
            LOGGER.exception("Judge failed for item #%d id=%s", idx, item.get("id"))
            judge_payload = {
                "response_fully_answers_question": False,
                "response_requires_more_input_data": False,
                "response_failed_backend_problems": True,
                "response_failed_tools_useless": False,
                "judge_reasons": {
                    "response_fully_answers_question": "",
                    "response_requires_more_input_data": "",
                    "response_failed_backend_problems": f"Judge execution failed: {exc}",
                    "response_failed_tools_useless": "",
                },
            }

        merged = dict(item)
        merged["llm_judges"] = judge_payload
        judged_items.append(merged)

    out_path = Path(args.output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(judged_items, ensure_ascii=False, indent=2), encoding="utf-8")
    LOGGER.info("Saved %d judged items to %s", len(judged_items), out_path)


if __name__ == "__main__":
    main()
